fix: Adding graceful tauri launch for linux

diff --git a/src-tauri/sidecar/trame-x86_64-unknown-linux-gnu b/src-tauri/sidecar/trame-x86_64-unknown-linux-gnu
--- a/src-tauri/sidecar/trame-x86_64-unknown-linux-gnu
+++ b/src-tauri/sidecar/trame-x86_64-unknown-linux-gnu
@@ -1,5 +1,13 @@
 #!/bin/bash
-rootdir=`dirname $0`
-rootdir=`cd $rootdir && pwd`
+basedir=$(cd "$(dirname "$0")/../lib" && pwd)
 
-$rootdir/server/server $@
+if [ -d "$basedir/quickview" ]; then
+    rootdir="$basedir/quickview"
+elif [ -d "$basedir/quick-view" ]; then
+    rootdir="$basedir/quick-view"
+else
+    echo "Error: Could not find quickview or quick-view directory in $basedir" >&2
+    exit 1
+fi
+
+"$rootdir/server/server" "$@"
